### ISSUE TITLE
Use pip for packaging

### ISSUE THREAD

**Issue by huanghao** [01org/iris-panel#2]
Now we have ansible playbook for deployment. However it needs rpm package, and there are some post-scripts in our spec file. If we want to switch to github and using pip as packaging solution. We need change ansible to adapt it.

**Comment by huanghao** [comment]
in spec file, we do the following things besides building and packaging:
1. add iris user and iris group
2. make two dirs: /srv/www/iris/media, /srv/www/iris/static
3. run python manage.py collectstatic
4. install /etc/apache2/vhosts.d/iris.conf
5. install /srv/www/iris/wsgi.py
6. install jquery-multi-select lib into static dir
7. install iris static files
8. generate django secret file
9. restart apache

Most of them are should be done by Ansible.

**Comment by huanghao** [comment]
If we install all requirements by pip, then we don't need to build rpm package.
We could use pypi to release, then iris can also be installed by pip.

**Comment by 117111302** [comment]
:+1:

**Comment by 117111302** [comment]
Can we maintain the playbooks in this repository?

**Comment by huanghao** [comment]
@117111302  There are many roles also, and we also have a private repo containing production host vars. So I don't think it's easy to move them here.

**Comment by 117111302** [comment]
Got it!

**Comment by huanghao** [comment]
change#17019 should fix point1

**Comment by huanghao** [comment]
change#17020 should fix point2

**Comment by 117111302** [comment]
Do we need ansible to install the scripts files under iris/bin/ ?

**Comment by huanghao** [comment]
change#17021 should fix point4 and 5

**Comment by huanghao** [comment]
@117111302 I think setup.py is proper place for it.

**Comment by huanghao** [comment]
Hi guys,
Please help to review those unmerged patches and test current playbook.
If everything is fine, I will close this issue.
Thanks!

**Comment by huanghao** [comment]
All patches mentioned are all merged. I will close it.
